name: Deploying

on:
  push:
    branches: [master]

jobs:
  deploying:
    runs-on: ubuntu-latest

    steps:
      - name: git checkout main
        uses: actions/checkout@v2

      - name: node install
        uses: actions/setup-node@v2
        with:
          node-version: 15.x
      - name: clean install
        run: npm ci

      - name: build
        run: npm run build
        env:
          CI: false

      - name: deploy
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          branch: built-page
          folder: build