name: Deploying

on:
  push:
    branches: [master]

jobs:
  deploying:
    runs-on: ubuntu-latest

    steps:
      - name: git checkout master
        uses: actions/checkout@v2

      - name: node install
        uses: actions/setup-node@v2
        with:
          node-version: 15.x
      - name: clean install
        run: |
          npm ci
          npm install -g license-report

      - name: licenses
        run: npm run licenses:ci

      - name: build
        run: npm run build
        env:
          CI: false

      - name: test
        run: npm run test:ci

      - name: deploy
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          branch: built-page
          folder: build

      - name: collect artifacts
        uses: actions/upload-artifact@v2
        with:
          name: artifacts
          path: |
            coverage/lcov-report
            licenses.csv
          if-no-files-found: error